### ISSUE TITLE
New API: Similar to EASTL::hash_map::find_as

### ISSUE THREAD

**Issue by ArnoChenFx** [martinus/unordered_dense#106]
I would like to request the addition of a new API that is similar to EASTL::hash_map::find_as. This new API would provide a convenient way to search for a specific value in an unordered_dense::map using a custom comparison function.

references:
https://github.com/electronicarts/EASTL/blob/05f4b4aef33f2f3ded08f19fa97f5a27ff35ff9f/include/EASTL/hash_map.h#L84
https://github.com/electronicarts/EASTL/blob/05f4b4aef33f2f3ded08f19fa97f5a27ff35ff9f/include/EASTL/internal/hashtable.h#L1075

**Comment by martinus** [comment]
I don't think that is needed, this can be done with `is_transparent` feature. See here: https://github.com/martinus/unordered_dense#324-heterogeneous-overloads-using-is_transparent
