### ISSUE TITLE
[BUG] Assignment from value to value not working for non-trivial types

### ISSUE THREAD

**Issue by dsiroky** [martinus/unordered_dense#115]
Hi! This issues seems to appear only if the value is of a non-trivial type.

This code
```
    ankerl::unordered_dense::map<int, std::string> m{};
    m[1] = "abc";
    m[2] = m[1];
    std::cout << '"' << m[1] << "\"\n";
    std::cout << '"' << m[2] << "\"\n";
```
prints
```
"abc"
""
```
Expected output is
```
"abc"
"abc"
```

If I "pre-create" the value in the map then it works:
```
    ankerl::unordered_dense::map<int, std::string> m{};
    m[1] = "abc";
    m[2]; // pre-create
    m[2] = m[1];
    std::cout << '"' << m[1] << "\"\n";
    std::cout << '"' << m[2] << "\"\n";

```

**System:**
 - OS: Linux
 - Compiler: g++ 13.2, clang++ 16.0.6
 - unordered_dense git commit d911053e390

**Comment by martinus** [comment]
Hi @dsiroky, thanks for the bug report! This seems to work for the try_emplace methods, but not for operator[]. I'll have a look

**Comment by glebm** [comment]
A repro test case for `test/assignment_combinations.cpp`:

```c++
TEST_CASE_MAP("assignment_combinations_11", int, std::string) {
    map_t m;
    m[1] = "abc";
    m[2] = m[1];
    REQUIRE(m[1] == "abc");
    REQUIRE(m[2] == "abc");
}
```

**Comment by glebm** [comment]
Let me rewrite the failing example above to an equivalent order of operations:

```c++
std::string &a = m[1];
std::string &b = m[2];
b = a;
```

The problem is that the reference to `a` is invalidated when we insert `b`.

**Comment by martinus** [comment]
@glebm you are of course right, there's nothing I can do about this since the map doesn't guarantee reference stability.
