### ISSUE TITLE
Does this support heterogeneous lookup?

### ISSUE THREAD

**Issue by iwubcode** [martinus/unordered_dense#29]
Does this `unordered_map` variant support heterogeneous lookup using the `is_transparent` flag?

If so, maybe add it to the docs?

**Comment by martinus** [comment]
Yes it does, no docs yet though. Search in the unit test and you'll find an example

**Comment by iwubcode** [comment]
Until there are docs, if anyone is interested the unit tests are here:  https://github.com/martinus/unordered_dense/blob/main/test/unit/transparent.cpp

Thanks @martinus for the speedy answer!
