### ISSUE TITLE
contains() should return 'bool' and not 'size_t'

### ISSUE THREAD

**Issue by Philippe91** [martinus/unordered_dense#31]
eg. from the standard:
https://en.cppreference.com/w/cpp/container/unordered_set/contains

returning a size_t causes a compiler warning.

**Comment by martinus** [comment]
Hi, thanks for reporting! No idea why I'm returning size_t, probably a copy and paste error from `counts()`. I'll fix it tonight and create a new release

**Comment by martinus** [comment]
fixed
