### ISSUE TITLE
[BUG] Copy constructor fails to compile when using custom container

### ISSUE THREAD

**Issue by antoine-fresse** [martinus/unordered_dense#39]
Hello,
I was experimenting with the custom container feature and encountered a bug. The copy constructor fails to compile when specifying a custom container for the AllocatorOrContainer template parameter
Here is a simple repro case :  https://godbolt.org/z/619WbTqxs

Thank you !

**Comment by martinus** [comment]
Hi, thanks for the reproducer! I'll have a look what's wrong

**Comment by martinus** [comment]
Can you give this a try if it works for you?
https://raw.githubusercontent.com/martinus/unordered_dense/2022-10-fix-custom-allocator-api/include/ankerl/unordered_dense.h

**Comment by antoine-fresse** [comment]
Yes it compiles now, thank you !

**Comment by martinus** [comment]
fixed by #40

**Comment by martinus** [comment]
I released v2.0.0 with that fix https://github.com/martinus/unordered_dense/releases/tag/v2.0.0
