### ISSUE TITLE
Question regarding collisions

### ISSUE THREAD

**Issue by jmbnyc** [martinus/unordered_dense#44]
How does this map handle collisions when the "distance" would exceed the max of 3 bytes. Resize? And what happens when there is poor hashing which collects a very collision rate. Your previous map would blow so wondering if this implementation addresses that short coming.

**Comment by martinus** [comment]
It would blow too, but with 3 bytes of collision resistance it will work until there are >16.7 million collisions for a single bucket. The map will become unusable slow long before that value can be reached, and it is only reachable when you have >16.7 million entries. For comparison, robin_hood map only had 128 possible positions for collision.  I consider this now a non-issue.

**Comment by jmbnyc** [comment]
Thanks for the context. I agree that with that many collisions, the map is not usable. I really like certain aspects of your new map but have to think carefully about using something with edge condition issues in production code, e.g. sometimes is hard to know if a map would grow beyond 4B entries in a code base that uses uint64_t (sometimes users do things that we would never expect). I prefer "slow" over "blow up" because "slow" is like socket push back - users complain but blow becomes: the system crashed or hung which is not a good place to be.
