### ISSUE TITLE
Define mapped_type only for ankerl::unordered_dense::map?

### ISSUE THREAD

**Issue by Andersama** [martinus/unordered_dense#48]
**Is your feature request related to a problem? Please describe.**
I'm not sure on what the standard says about the `mapped_type` definition or how it's used, but in the `zpp_bits` serialization library they're using it to detect the slight variation between the two containers. Intuitively to me it makes sense that `void` as a value for a key value structure would mean that you're really dealing with a set. Looking at cppreference it appears though the standard might be that `mapped_type` is specific to maps. 

Currently with the set and map being the same template `mapped_type` gets defined for both, and in `zpp_bits` this results in that library attempting to create a reference to `void` in order to iterate over key value pairs, which is a compiler error.

**Describe the solution you'd like**
If `mapped_type` is specific to maps in the standard use `detail::table` as a backing implementation where `mapped_type` is not defined. Then wrap that container for `set` and `map` where `map` has `mapped_type` defined.

**Comment by martinus** [comment]
Hi @Andersama! I've got a fix here where `mapped_type` is only defined for map: https://raw.githubusercontent.com/martinus/unordered_dense/2022-12-no-mapped_type-for-set/include/ankerl/unordered_dense.h

Can you give it a ary if this would work for your serializer? If it does, I'll create a new release with this fix.

**Comment by Andersama** [comment]
Wish I'd caught this earlier, I'm going to have to wait a few hours before I can test anything.

**Comment by Andersama** [comment]
Looks like it works, all good here with the edit.

**Comment by Andersama** [comment]
That's it. The tricky thing is I've had a few structs change layout from debug and release and I think empty base classes might be one of those things that gets toggled on and off. Fairly confident modern ones will for release. I'm going to have to check. I just didn't want to suggest something and then end up bloating your hash table.
