### ISSUE TITLE
[BUG] erase operation dosen't work for iterator

### ISSUE THREAD

**Issue by stillcold** [martinus/unordered_dense#50]
Hi guys,

It seams **erase** operation dosen't work for **iterator**.

I put my code here on [compiler exploer](https://gcc.godbolt.org/z/Gv3jEvn75).

As we can see, the code will not work in line 53, which should behavior just the same as line 25 does.

Please help me out.

Thanks in advance!

**Comment by martinus** [comment]
iterators are NOT stable. In line 42 you write `ret = umap.insert(mypair);`, and right after you insert something int the map with `umap["b"] = "c";`. This invalidates the iterator, you are not allowed to use `ret` any more.

**Comment by stillcold** [comment]
I see. Thanks very much!

When I use **robin_hood::unordered_node_map** instead of **ankerl::unordered_dense::map**, it is also fails.

Is there any work aound about this case?

**Comment by martinus** [comment]
Don't store iterators. They are also not stable for Std unordered_map

**Comment by martinus** [comment]
No, iterators are not stable. It's also not stable for std::unordered_map when it rehashes. It's simply not allowed to store iterators. Use pointers with std::unordered_map instead.
