### ISSUE TITLE
Question about reserve

### ISSUE THREAD

**Issue by MBkkt** [martinus/unordered_dense#61]
https://github.com/abseil/abseil-cpp/issues/906

I think it shouldn't (because it's kind of open addressing), but maybe?

**Comment by MBkkt** [comment]
Is it issue same for your hashtable?

It's not "feature request"

**Comment by martinus** [comment]
No rehashing, but insert/erase invalidates references & iterators.

**Comment by MBkkt** [comment]
if no rehashing (in case of reserve) why is it invalidates iterators in this case?

**Comment by martinus** [comment]
because its a robin-hood hashing with backward shift deletion https://programming.guide/robin-hood-hashing.html

**Comment by MBkkt** [comment]
I see thanks!
