### ISSUE TITLE
A comparison with your older robin-hood hashing library would be useful

### ISSUE THREAD

**Issue by purew** [martinus/unordered_dense#62]
I came to this repo from the unmaintained note in https://github.com/martinus/robin-hood-hashing

It would be very helpful if this README could compare this with that library and explain what the differences are, seeing as this is suggested as a replacement.

**Comment by martinus** [comment]
Well, the old version is something I don't want to maintain any more. It might be buggy (e.g. overflow exceptions)
unordered_dense is well maintain and has no know bugs, and a buch more features as described in the readme.
