### ISSUE TITLE
can't compiler with T=std::deque<std::unique<T>>

### ISSUE THREAD

**Issue by yanwei1983** [martinus/unordered_dense#63]
**Describe the bug**
can't compiler with T=std::deque<std::unique<T>>

**To Reproduce**
```
#include "https://raw.githubusercontent.com/martinus/unordered_dense/main/include/ankerl/unordered_dense.h"

#include <deque>
#include <memory>
#include <unordered_map>

using value_t = std::deque<std::unique_ptr<uint32_t>>;
ankerl::unordered_dense::map<uint32_t, value_t> test_map; //compiler error
std::unordered_map<uint32_t, value_t> test_map_std; //succ
```

**Comment by martinus** [comment]
Interesting, the problem boils down to this:

```cpp
using value_t = std::deque<std::unique_ptr<uint32_t>>;
using pair_t = std::pair<uint32_t, value_t>;
auto v = std::vector<pair_t>{};
v.reserve(100); // compile error
```

So the problem is this doesn't work for a vector with a pair that has a deque with unique_ptr...

**Comment by martinus** [comment]
I'm sorry, there's nothing I can do here. This seems to be a defect in the C++ stdlib. `std::deque` is not required that move constructor is `noexcept`, and for some reason using it as part of a `std::pair` causes this to fail.

I'm using an `std::vector` as the base for `unordered_map`, so this simply can't work.

**Comment by yanwei1983** [comment]
i change the value_t , it succ
```
struct value_t : public std::deque<std::unique_ptr<uint32_t>>
{
    value_t(value_t&&) noexcept = default;
};
```  
thanks

**Comment by martinus** [comment]
Ha, that's a nice workaround!
