### ISSUE TITLE
"conditional expression is constant" warnings due to using `if` where `if constexpr` is appropriate

### ISSUE THREAD

**Issue by VioletGiraffe** [martinus/unordered_dense#65]
There are 3 places in sparse_hash.h where MSVC gives the aforementioned warning (with `/W4` level which is my default). All the conditions are indeed purely compile-time and should be replaced with constexpr. Will you accept a pull request if I fix this?

For example: `if (sizeof(unsigned int) == sizeof(std::uint32_t))`

**Comment by martinus** [comment]
Sure, go ahead! 👍

**Comment by martinus** [comment]
Although I'm curious what the fix is, it sounds like an issue with Microsoft's stl

**Comment by VioletGiraffe** [comment]
I am very sorry, I have too many Guthub tabs open and reported the issue to the wrong repository.
