### ISSUE TITLE
Support for multiset / multimap versions?

### ISSUE THREAD

**Issue by jcelerier** [martinus/unordered_dense#66]
e.g. analoguous to the std::unordered_multi{set,map} ; is this on the roadmap / compatible with the design in any way?

**Comment by martinus** [comment]
It's not planned, and I never really needed these. You could have e.g use a std::vector as mapped value instead

**Comment by jcelerier** [comment]
hmmm, for unordered_multiset it wouldn't work - the "multi" is not only on the value but on the key

**Comment by martinus** [comment]
Thats true, but isn't a multiset basically a map where the value is a counter for the number of entries? Sure the API is different, but at least it's possible to have basically the same features

**Comment by kabicm** [comment]
`std::unordered_multimap` would be useful e.g. for implementing hash joins.

Do we know any performance comparison between e.g. `std::unordere_multimap<int, int>` vs `ankerl::unordered_dense::map<int, std:vector<int>>`?

I am curious if using the `std::vector` as the value would hurt the performance of `ankerl::unordered_dense::map`.

Also, is boost a hard dependency here?

Thanks a lot for your help!
