### ISSUE TITLE
Compilation error when min/max macros are defined

### ISSUE THREAD

**Issue by sb362** [martinus/unordered_dense#68]
**Is your feature request related to a problem? Please describe.**
Some headers (notably `Windows.h`) define the macros `min` and `max`, which causes compilation errors if you use functions like `std::min()` or `std::numeric_limits<int>::max()`. Trying to compile
```cpp
#include <Windows.h>
#include "unordered_dense.h"

int main() {
  ankerl::unordered_dense::map<int, int> abc;
  return 0;
}
```
results in several errors:
![image](https://user-images.githubusercontent.com/38133735/221010948-820dc4fc-1358-469e-9398-7b6147ab2aa0.png)

**Describe the solution you'd like**
Should be able to compile even if `min`/`max` are defined as macros. You can get around this by `#undef`ing `min`/`max` before including `unordered_dense.h`, but I think a much better solution is wrap any calls to functions named `min`/`max` in parentheses. This is what they do in Abseil: https://github.com/abseil/abseil-cpp/blob/1ae9b71c474628d60eb251a3f62967fe64151bb2/absl/random/internal/pool_urbg.h#L96
For example:
```cpp
[[nodiscard]] static constexpr auto calc_num_buckets(uint8_t shifts) -> size_t {
    return (std::min)(max_bucket_count(), size_t{1} << (64U - shifts));
}
```
will successfully compile even if `min`/`max` are defined.

**Comment by martinus** [comment]
You can use `#define NOMINMAX` before including Windows.h

**Comment by martinus** [comment]
Ah, I see you already have a PR ready, thanks!

**Comment by sb362** [comment]
> You can use `#define NOMINMAX` before including Windows.h

Good to know, but in my case I have no idea where Windows.h is even included.. so I decided to fix it here instead.
