### ISSUE TITLE
API extensions supporting insert/find/erase/etc. when a hash is already available

### ISSUE THREAD

**Issue by jeremyong** [martinus/unordered_dense#71]
First, thanks for the library! A key feature I've grown accustomed to (working with my own containers, as well as many specialized containers coming from game engine development) is the ability to invoke various API methods when a hash is already available. This sort of scenario is quite common, imagine you have a string identifier of some sort, and a number of structures keyed to the same identifier. Ideally, you could compute the hash once, and then reuse the result (or even cache it where appropriate) to avoid needing to re-hash the string on every operation.

When I implemented this in the past, usually it involved some light refactoring to split operations into a version accepting a hash, and a version that didn't (which would compute a hash and then forward the call to the hash-accepting version). The savings are, of course, dependent on your hash function, and the size of the input.

This API has a footgun that users need to be aware of, which is that the hash function used _must_ match the hash function used by the container, for obvious reasons. For this reason, I recommend providing a helper function on the map/set structures to compute the hash for a given input. This takes any guesswork out of the usage, and reduces the risk of API misuse.

Cheers!
Jeremy

**Comment by martinus** [comment]
Hi, I believe what you want is already possible since the map already has full support for heterogenous lookups. This proposal describes how to use it: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1661r1.html

See also this: https://github.com/martinus/unordered_dense#314-heterogeneous-overloads-using-is_transparent

I have not tried that yet though.
