### ISSUE TITLE
[BUG] erase_if returns an incorrect value

### ISSUE THREAD

**Issue by sultim-t** [martinus/unordered_dense#76]
**Describe the bug**
`erase_if` returns `current_size - old_size` which is a negative value that is cast to an unsigned `size_t` on return.
https://github.com/martinus/unordered_dense/blob/fefa511ca94b145eca1e102da46ecb27cd03846c/include/ankerl/unordered_dense.h#L1910

**To Reproduce**
1. Call `erase_if`

**Expected behavior**
`erase_if` should return `old_size - current_size`, not `current_size - old_size`

**System (please complete the following information):**
 - OS: Windows
 - Compiler: MSVC
 - Version 19.34.31937

**Additional context**
None.

**Comment by martinus** [comment]
Ha, you are of course correct, this is a bug. It seems whenever I don't have a test for something I'll do it wrong. I'll create a new release with the fix.

**Comment by martinus** [comment]
I've created release v4.0.1 with this fix. Thanks!
