### ISSUE TITLE
[BUG] Can't compiler in c++20 module

### ISSUE THREAD

**Issue by jz315** [martinus/unordered_dense#84]
**Describe the bug**

**To Reproduce**
Test.ixx
```
module;
#include"unordered_dense.h"
#include<string_view>
export module ModuleTest;

export struct Test
{
	ankerl::unordered_dense::map<std::string_view, int>m;
};
```
main.cpp
```
import ModuleTest;
int main() {
    Test test;
    test.m.emplace("1", 1);
    return 0;
}
```
Error
`C2129 Static function "unsigned __int64 ankerl::unordered_dense::v4_0_4::detail::wyhash::hash(uint64_t)" declared but not defined`
**Expected behavior**

**System (please complete the following information):**
 - OS: Windows
 - Compiler: MSVC
 - Version: lastest

**Additional context**
After searching, I found `export` keyword cannot export with internal links.
Remove `static` keyword, it still unable to compile.
`binary 'operator==' : 'const _Ty' does not define this operator or a conversion to a type acceptable to the predefined operator`
Replace `unordered_dense.h` to `unordered_map`,  it can compile normally.

**Comment by martinus** [comment]
Hi @jz315, unfortunately I have zero experience with modules. I've now tried to create a `ankerl_unordered_dense.cpp` which creates a module for unordered_dense, and this seems to work at least for clang++. 

Can you have a look at the branch https://github.com/martinus/unordered_dense/tree/2023-08-module-support

There I have a file https://github.com/martinus/unordered_dense/blob/2023-08-module-support/src/ankerl_unordered_dense.cpp which you should be able to compile to create the module.

Then you can use `import ankerl_unordered_dense;` and should be able to use `ankerl::unordered_dense`; see the example program here: https://github.com/martinus/unordered_dense/blob/2023-08-module-support/test/modules/module_test.cpp

Can you give this a try if it works in MSVC?

**Comment by jz315** [comment]
It works well.
Thank you so much.

**Comment by martinus** [comment]
Awesome, I'll create a new release.
