### ISSUE TITLE
[ Question ] How does this interface compare to the one defined in C++23

### ISSUE THREAD

**Issue by iwubcode** [martinus/unordered_dense#99]
Curious how close the interface is compared with the future std implementations in flat_map and flat_set?

I can look this up myself of course but also wondered if we should put some details in the README.

**Comment by martinus** [comment]
I think it should be quite different, flat_map is basically a sorted array and doesn't hash

**Comment by iwubcode** [comment]
Apologies, I was multi-tasking when someone asked me this question and I said I'd forward it.  If I had thought about it, it would make sense this is a different approach.  Thanks for taking the time to respond!!
